#!/bin/bash
# 
# Written by Lars Larsson <lars@lars.la>
#

if [ ! $1 ]; then
	echo "Usage: $0 <base name of tar archive>"
	exit
fi

DATE=$(date +%s)

if [ -a /tmp/restore-$DATE.tar ]; then
	echo "ERROR: Looks like there is another restore-job running at the same time, exiting."
	exit
fi

if [ ! -f $1-1.tar ]; then
	echo "ERROR: no such file: $1-1.tar, maybe you didn't give me the correct base name?"
	exit
fi

export TAR_BASE_VOL=$1


ln -s $1-1.tar /tmp/restore-$DATE.tar
tar -M -F /usr/local/share/backup/switchtape.sh -tvf /tmp/restore-$DATE.tar

rm /tmp/restore-$DATE.tar
